development:
  adapter: postgresql
  encoding: utf8
  database: sterne_development
  pool: 5
  username: sterne 
  password: sterne

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sterne_test
  pool: 5
  username: sterne
  password: sterne

production:
  adapter: postgresql
  encoding: utf8
  database: sterne_production
  pool: 5
  username: sterne
  password: sterne

cucumber:
  <<: *TEST
