require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlanetsController do

  # This should return the minimal set of attributes required to create a valid
  # Planet. As you add validations to Planet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all planets as @planets" do
      planet = Planet.create! valid_attributes
      get :index
      assigns(:planets).should eq([planet])
    end
  end

  describe "GET show" do
    it "assigns the requested planet as @planet" do
      planet = Planet.create! valid_attributes
      get :show, :id => planet.id.to_s
      assigns(:planet).should eq(planet)
    end
  end

  describe "GET new" do
    it "assigns a new planet as @planet" do
      get :new
      assigns(:planet).should be_a_new(Planet)
    end
  end

  describe "GET edit" do
    it "assigns the requested planet as @planet" do
      planet = Planet.create! valid_attributes
      get :edit, :id => planet.id.to_s
      assigns(:planet).should eq(planet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Planet" do
        expect {
          post :create, :planet => valid_attributes
        }.to change(Planet, :count).by(1)
      end

      it "assigns a newly created planet as @planet" do
        post :create, :planet => valid_attributes
        assigns(:planet).should be_a(Planet)
        assigns(:planet).should be_persisted
      end

      it "redirects to the created planet" do
        post :create, :planet => valid_attributes
        response.should redirect_to(Planet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved planet as @planet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Planet.any_instance.stub(:save).and_return(false)
        post :create, :planet => {}
        assigns(:planet).should be_a_new(Planet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Planet.any_instance.stub(:save).and_return(false)
        post :create, :planet => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested planet" do
        planet = Planet.create! valid_attributes
        # Assuming there are no other planets in the database, this
        # specifies that the Planet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Planet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => planet.id, :planet => {'these' => 'params'}
      end

      it "assigns the requested planet as @planet" do
        planet = Planet.create! valid_attributes
        put :update, :id => planet.id, :planet => valid_attributes
        assigns(:planet).should eq(planet)
      end

      it "redirects to the planet" do
        planet = Planet.create! valid_attributes
        put :update, :id => planet.id, :planet => valid_attributes
        response.should redirect_to(planet)
      end
    end

    describe "with invalid params" do
      it "assigns the planet as @planet" do
        planet = Planet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Planet.any_instance.stub(:save).and_return(false)
        put :update, :id => planet.id.to_s, :planet => {}
        assigns(:planet).should eq(planet)
      end

      it "re-renders the 'edit' template" do
        planet = Planet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Planet.any_instance.stub(:save).and_return(false)
        put :update, :id => planet.id.to_s, :planet => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested planet" do
      planet = Planet.create! valid_attributes
      expect {
        delete :destroy, :id => planet.id.to_s
      }.to change(Planet, :count).by(-1)
    end

    it "redirects to the planets list" do
      planet = Planet.create! valid_attributes
      delete :destroy, :id => planet.id.to_s
      response.should redirect_to(planets_url)
    end
  end

end
