require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UniversesController do

  # This should return the minimal set of attributes required to create a valid
  # Universe. As you add validations to Universe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all universes as @universes" do
      universe = Universe.create! valid_attributes
      get :index
      assigns(:universes).should eq([universe])
    end
  end

  describe "GET show" do
    it "assigns the requested universe as @universe" do
      universe = Universe.create! valid_attributes
      get :show, :id => universe.id.to_s
      assigns(:universe).should eq(universe)
    end
  end

  describe "GET new" do
    it "assigns a new universe as @universe" do
      get :new
      assigns(:universe).should be_a_new(Universe)
    end
  end

  describe "GET edit" do
    it "assigns the requested universe as @universe" do
      universe = Universe.create! valid_attributes
      get :edit, :id => universe.id.to_s
      assigns(:universe).should eq(universe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Universe" do
        expect {
          post :create, :universe => valid_attributes
        }.to change(Universe, :count).by(1)
      end

      it "assigns a newly created universe as @universe" do
        post :create, :universe => valid_attributes
        assigns(:universe).should be_a(Universe)
        assigns(:universe).should be_persisted
      end

      it "redirects to the created universe" do
        post :create, :universe => valid_attributes
        response.should redirect_to(Universe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved universe as @universe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Universe.any_instance.stub(:save).and_return(false)
        post :create, :universe => {}
        assigns(:universe).should be_a_new(Universe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Universe.any_instance.stub(:save).and_return(false)
        post :create, :universe => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested universe" do
        universe = Universe.create! valid_attributes
        # Assuming there are no other universes in the database, this
        # specifies that the Universe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Universe.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => universe.id, :universe => {'these' => 'params'}
      end

      it "assigns the requested universe as @universe" do
        universe = Universe.create! valid_attributes
        put :update, :id => universe.id, :universe => valid_attributes
        assigns(:universe).should eq(universe)
      end

      it "redirects to the universe" do
        universe = Universe.create! valid_attributes
        put :update, :id => universe.id, :universe => valid_attributes
        response.should redirect_to(universe)
      end
    end

    describe "with invalid params" do
      it "assigns the universe as @universe" do
        universe = Universe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Universe.any_instance.stub(:save).and_return(false)
        put :update, :id => universe.id.to_s, :universe => {}
        assigns(:universe).should eq(universe)
      end

      it "re-renders the 'edit' template" do
        universe = Universe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Universe.any_instance.stub(:save).and_return(false)
        put :update, :id => universe.id.to_s, :universe => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested universe" do
      universe = Universe.create! valid_attributes
      expect {
        delete :destroy, :id => universe.id.to_s
      }.to change(Universe, :count).by(-1)
    end

    it "redirects to the universes list" do
      universe = Universe.create! valid_attributes
      delete :destroy, :id => universe.id.to_s
      response.should redirect_to(universes_url)
    end
  end

end
